// Conteúdo inicial AM Moreira. Depois do bootstrap, tudo é editável no CMS e persistido no MongoDB.
export const seedData = {
  settings: [{
    id:'company', name:'AM Moreira', brand:'AM Shoes by Sapatarias Moreira',
    description:'Moda, conforto e qualidade. Uma montra digital da AM Moreira.',
    logo:'/brand/logo-preto.png', logoLight:'/brand/logo-branco.png', favicon:'/favicon.ico',
    email:'', phones:['914 199 067','914 765 391'], website:'amoreirashoes.pt',
    instagram:'@a.mshoes', instagramUrl:'https://instagram.com/a.mshoes',
    locations:['Paredes','Marco de Canaveses','Rio de Moinhos','Castelo de Paiva','Baião','Lousada','Cinfães','Couto','Penafiel'],
    seoTitle:'AM Moreira — Moda, conforto e qualidade',
    metaDescription:'Conheça a AM Moreira, os seus produtos, coleções, fabrico e presença em feiras.',
    contactSubjects:['Informações gerais','Informação sobre produto','Apresentar uma ideia','Apresentar um projeto','Conversa comercial','Outra questão'],
    contactCtaLabel:'Contactar', contactCtaUrl:'/contacto',
    public:true, status:'published',
  }],
  categories: [
    {id:'footwear',name:'Calçado',slug:'calcado',order:1,status:'published'},
    {id:'boots',name:'Botas',slug:'botas',order:2,status:'published'},
    {id:'bags',name:'Malas',slug:'malas',order:3,status:'published'},
    {id:'leather-goods',name:'Marroquinaria',slug:'marroquinaria',order:4,status:'published'},
    {id:'other',name:'Outros',slug:'outros',order:5,status:'published'},
  ],
  menus: [['Início','/'],['Sobre nós','/sobre'],['Fabrico','/fabrico'],['Produtos','/produtos'],['Coleções','/colecoes'],['Feiras','/eventos'],['Galeria','/galeria']].map(([label,url],index)=>({id:`menu-${index+1}`,label,url,location:'header',order:index+1,status:'active'})),
  pages: [
    {id:'page-home',title:'Início',slug:'home',status:'published',seoTitle:'AM Moreira — Moda, conforto e qualidade',metaDescription:'Conheça a AM Moreira, os seus produtos, coleções, fabrico e presença em feiras.',indexable:true},
    {id:'page-about',title:'Sobre nós',slug:'sobre',status:'published',seoTitle:'Sobre nós — AM Moreira',metaDescription:'Conheça a identidade AM Moreira.',indexable:true},
    {id:'page-production',title:'Fabrico',slug:'fabrico',status:'published',seoTitle:'Fabrico — AM Moreira',metaDescription:'Conheça o processo e fabrico AM Moreira.',indexable:true},
    {id:'page-contact',title:'Contactos',slug:'contacto',status:'published',seoTitle:'Contactos — AM Moreira',metaDescription:'Fale com a AM Moreira.',indexable:true},
    {id:'page-products',title:'Produtos',slug:'produtos',status:'published',seoTitle:'Produtos — AM Moreira',metaDescription:'Catálogo informativo AM Moreira.',indexable:true},
    {id:'page-collections',title:'Coleções',slug:'colecoes',status:'published',seoTitle:'Coleções — AM Moreira',metaDescription:'Coleções AM Moreira.',indexable:true},
    {id:'page-events',title:'Feiras & Eventos',slug:'eventos',status:'published',seoTitle:'Feiras & Eventos — AM Moreira',metaDescription:'Presença da AM Moreira em feiras e eventos.',indexable:true},
    {id:'page-gallery',title:'Galeria',slug:'galeria',status:'published',seoTitle:'Galeria — AM Moreira',metaDescription:'Galeria visual AM Moreira.',indexable:true},
  ],
  contentBlocks: [
    {id:'home-hero',pageSlug:'home',type:'hero',eyebrow:'AM Shoes · Sapatarias Moreira',title:'Estilo que se sente. Qualidade que permanece.',content:'Uma marca portuguesa focada na moda, no conforto e na qualidade, presente perto de si.',image:'/brand/cartao-visita.jpg',items:['Explorar produtos|/produtos','Falar connosco|/contacto'],order:1,status:'published'},
    {id:'home-brand',pageSlug:'home',type:'text-image',eyebrow:'A marca',title:'Proximidade, cuidado e identidade.',content:'A AM Moreira apresenta produtos e trabalhos selecionados numa experiência simples, visual e próxima.',image:'/brand/logo-branco.png',order:2,status:'published'},
    {id:'home-products',pageSlug:'home',type:'products',eyebrow:'Catálogo informativo',title:'Produtos em destaque',content:'Uma seleção visual, sem preços ou compra online. Para saber mais, fale diretamente com a nossa equipa.',order:3,status:'published'},
    {id:'home-events',pageSlug:'home',type:'events',eyebrow:'Onde estamos',title:'Feiras & Eventos',content:'Consulte onde poderá encontrar a AM Moreira.',order:4,status:'published'},
    {id:'home-contact',pageSlug:'home',type:'form',eyebrow:'Começar uma conversa',title:'Tem uma dúvida, ideia ou projeto?',content:'Partilhe connosco. A mensagem fica disponível no CMS para acompanhamento pela equipa.',order:5,status:'published'},
    {id:'about-hero',pageSlug:'sobre',type:'page-header',eyebrow:'Identidade',title:'Uma marca próxima, feita para ser descoberta.',content:'Conheça a identidade, os valores e a presença da AM Moreira.',order:1,status:'published'},
    {id:'about-text',pageSlug:'sobre',type:'text-image',eyebrow:'AM Shoes',title:'Moda, conforto e qualidade.',content:'A AM Moreira apresenta a sua identidade, os seus produtos e a sua presença de forma contemporânea, simples e visual.',image:'/brand/logo-branco.png',order:2,status:'published'},
    {id:'production-hero',pageSlug:'fabrico',type:'page-header',eyebrow:'Processo',title:'Do detalhe à peça final.',content:'Materiais, técnicas, instalações e etapas do processo AM Moreira.',order:1,status:'published'},
    {id:'production-text',pageSlug:'fabrico',type:'text',eyebrow:'Fabrico',title:'Conteúdo em preparação',content:'A equipa poderá completar esta área no CMS com informação e imagens confirmadas do processo de fabrico.',order:2,status:'published'},
    {id:'contact-hero',pageSlug:'contacto',type:'page-header',eyebrow:'Fale connosco',title:'Vamos começar uma conversa.',content:'Dúvidas, informação sobre produtos, ideias, projetos ou uma conversa comercial.',order:1,status:'published'},
    {id:'contact-form',pageSlug:'contacto',type:'form',eyebrow:'Contactos',title:'Envie-nos uma mensagem',content:'Responderemos assim que possível.',order:2,status:'published'},
    {id:'products-header',pageSlug:'produtos',type:'page-header',eyebrow:'Catálogo informativo',title:'Produtos',content:'Descubra exemplos da seleção AM Moreira. Para informações, disponibilidade ou projetos, contacte-nos.',order:1,status:'published'},
    {id:'collections-header',pageSlug:'colecoes',type:'page-header',eyebrow:'Editorial',title:'Coleções',content:'Narrativas visuais organizadas por ano, estação ou conceito.',order:1,status:'published'},
    {id:'events-header',pageSlug:'eventos',type:'page-header',eyebrow:'Presença da marca',title:'Feiras & Eventos',content:'Consulte onde poderá encontrar a AM Moreira.',order:1,status:'published'},
    {id:'gallery-header',pageSlug:'galeria',type:'page-header',eyebrow:'Universo visual',title:'Galeria',content:'Produtos, detalhes, presença e identidade AM Moreira.',order:1,status:'published'},
  ],
  products: [], collections: [], events: [], gallery: [], contacts: [], auditLogs: [], users: [],
}
