// Conteúdo inicial AM Moreira. Depois do bootstrap, tudo é editável no CMS e persistido no MongoDB.
export const seedData = {
  settings: [{
    id:'company', name:'AM Moreira', brand:'AM Shoes by Sapatarias Moreira',
    description:'Moda, conforto e qualidade. Uma montra digital da AM Moreira.',
    logo:'/brand/logo-preto.png', logoLight:'/brand/logo-branco.png', favicon:'/favicon.ico',
    email:'', phones:['914 199 067','914 765 391'], website:'amoreirashoes.pt',
    instagram:'@a.mshoes', instagramUrl:'https://instagram.com/a.mshoes',
    locations:['Paredes','Marco de Canaveses','Rio de Moinhos','Castelo de Paiva','Baião','Lousada','Cinfães','Couto','Penafiel'],
    seoTitle:'AM Moreira — Moda, conforto e qualidade',
    metaDescription:'Conheça a AM Moreira, os seus produtos, coleções, fabrico e presença em feiras.',
    contactSubjects:['Informações gerais','Informação sobre produto','Apresentar uma ideia','Apresentar um projeto','Conversa comercial','Outra questão'],
    contactCtaLabel:'Contactar', contactCtaUrl:'/contacto',
    public:true, status:'published',
  }],
  categories: [
    {id:'footwear',name:'Calçado',slug:'calcado',order:1,status:'published'},
    {id:'boots',name:'Botas',slug:'botas',order:2,status:'published'},
    {id:'bags',name:'Malas',slug:'malas',order:3,status:'published'},
    {id:'leather-goods',name:'Marroquinaria',slug:'marroquinaria',order:4,status:'published'},
    {id:'other',name:'Outros',slug:'outros',order:5,status:'published'},
  ],
  menus: [['Início','/'],['Sobre nós','/sobre'],['Fabrico','/fabrico'],['Produtos','/produtos'],['Coleções','/colecoes'],['Feiras','/eventos'],['Galeria','/galeria']].map(([label,url],index)=>({id:`menu-${index+1}`,label,url,location:'header',order:index+1,status:'active'})),
  pages: [
    {id:'page-home',title:'Início',slug:'home',status:'published',seoTitle:'AM Moreira — Moda, conforto e qualidade',metaDescription:'Conheça a AM Moreira, os seus produtos, coleções, fabrico e presença em feiras.',indexable:true},
    {id:'page-about',title:'Sobre nós',slug:'sobre',status:'published',seoTitle:'Sobre nós — AM Moreira',metaDescription:'Conheça a identidade AM Moreira.',indexable:true},
    {id:'page-production',title:'Fabrico',slug:'fabrico',status:'published',seoTitle:'Fabrico — AM Moreira',metaDescription:'Conheça o processo e fabrico AM Moreira.',indexable:true},
    {id:'page-contact',title:'Contactos',slug:'contacto',status:'published',seoTitle:'Contactos — AM Moreira',metaDescription:'Fale com a AM Moreira.',indexable:true},
    {id:'page-products',title:'Produtos',slug:'produtos',status:'published',seoTitle:'Produtos — AM Moreira',metaDescription:'Catálogo informativo AM Moreira.',indexable:true},
    {id:'page-collections',title:'Coleções',slug:'colecoes',status:'published',seoTitle:'Coleções — AM Moreira',metaDescription:'Coleções AM Moreira.',indexable:true},
    {id:'page-events',title:'Feiras & Eventos',slug:'eventos',status:'published',seoTitle:'Feiras & Eventos — AM Moreira',metaDescription:'Presença da AM Moreira em feiras e eventos.',indexable:true},
    {id:'page-gallery',title:'Galeria',slug:'galeria',status:'published',seoTitle:'Galeria — AM Moreira',metaDescription:'Galeria visual AM Moreira.',indexable:true},
  ],
  contentBlocks: [
    {id:'home-hero',pageSlug:'home',type:'hero',eyebrow:'AM Shoes · Sapatarias Moreira',title:'Estilo que se sente. Qualidade que permanece.',content:'Uma marca portuguesa focada na moda, no conforto e na qualidade, presente perto de si.',image:'/brand/cartao-visita.jpg',items:['Explorar produtos|/produtos','Falar connosco|/contacto'],order:1,status:'published'},
    {id:'home-brand',pageSlug:'home',type:'text-image',eyebrow:'A marca',title:'Proximidade, cuidado e identidade.',content:'Na AM Moreira, cada coleção nasce da procura pelo equilíbrio entre conforto, detalhe e uma presença que acompanha o dia a dia. Trabalhamos uma seleção pensada para quem valoriza qualidade, versatilidade e uma relação próxima com a marca.',image:'/brand/logo-branco.png',order:2,status:'published'},
    {id:'home-products',pageSlug:'home',type:'products',eyebrow:'Catálogo informativo',title:'Produtos em destaque',content:'Uma seleção visual, sem preços ou compra online. Para saber mais, fale diretamente com a nossa equipa.',order:3,status:'published'},
    {id:'home-collections',pageSlug:'home',type:'cta',eyebrow:'Coleções',title:'Peças que acompanham o seu ritmo.',content:'Descubra propostas organizadas por estilo, momento e inspiração. Cada coleção pode ser atualizada pela equipa no CMS.',items:['Ver coleções|/colecoes'],order:4,status:'published'},
    {id:'home-events',pageSlug:'home',type:'events',eyebrow:'Onde estamos',title:'Feiras & Eventos',content:'Acompanhe os próximos pontos de encontro e fale connosco presencialmente.',order:5,status:'published'},
    {id:'home-contact',pageSlug:'home',type:'form',eyebrow:'Começar uma conversa',title:'Tem uma dúvida, ideia ou projeto?',content:'Partilhe connosco o que procura. A sua mensagem chega diretamente à equipa através do CMS.',order:6,status:'published'},
    {id:'about-hero',pageSlug:'sobre',type:'page-header',eyebrow:'Identidade',title:'Uma marca próxima, feita para ser descoberta.',content:'A AM Moreira junta experiência, atenção ao detalhe e uma abordagem próxima para criar uma seleção com identidade.',order:1,status:'published'},
    {id:'about-text',pageSlug:'sobre',type:'text-image',eyebrow:'AM Shoes',title:'Moda, conforto e qualidade.',content:'Acreditamos que escolher bem começa por sentir confiança. Por isso, apresentamos uma seleção cuidada, pensada para diferentes estilos e momentos, sem perder a proximidade que nos caracteriza.\n\nDo atendimento à descoberta de cada peça, queremos tornar a experiência simples, inspiradora e genuína.',image:'/brand/logo-branco.png',order:2,status:'published'},
    {id:'about-values',pageSlug:'sobre',type:'text',eyebrow:'O que nos guia',title:'Cuidado em cada escolha.',content:'Qualidade: procuramos peças que façam sentido no presente e permaneçam relevantes.\n\nProximidade: valorizamos ouvir, aconselhar e criar relações duradouras.\n\nIdentidade: escolhemos propostas com personalidade, conforto e atenção aos detalhes.',order:3,status:'published'},
    {id:'about-cta',pageSlug:'sobre',type:'cta',eyebrow:'Fale connosco',title:'Quer conhecer melhor a AM Moreira?',content:'Estamos disponíveis para esclarecer questões sobre produtos, disponibilidade ou futuras colaborações.',items:['Entrar em contacto|/contacto'],order:4,status:'published'},
    {id:'production-hero',pageSlug:'fabrico',type:'page-header',eyebrow:'Processo',title:'Do detalhe à peça final.',content:'Uma visão cuidada sobre materiais, escolhas e acabamentos que valorizam cada produto.',order:1,status:'published'},
    {id:'production-text',pageSlug:'fabrico',type:'text',eyebrow:'Fabrico',title:'Rigor, atenção e qualidade.',content:'Cada produto reúne várias decisões: a seleção de materiais, o conforto, a construção e o acabamento final. É esse cuidado que procuramos refletir em cada coleção apresentada pela AM Moreira.\n\nEsta página foi preparada para a equipa acrescentar processos, imagens, histórias e informações técnicas diretamente no CMS, à medida que o conteúdo estiver disponível.',order:2,status:'published'},
    {id:'production-detail',pageSlug:'fabrico',type:'text',eyebrow:'A nossa abordagem',title:'Pensado para ser usado e apreciado.',content:'Da primeira escolha ao resultado final, procuramos reunir conforto, funcionalidade e uma estética cuidada. A informação desta área é totalmente editável no CMS, para que a equipa possa partilhar novidades, imagens e detalhes reais de cada processo.',order:3,status:'published'},
    {id:'production-cta',pageSlug:'fabrico',type:'cta',eyebrow:'Conheça a seleção',title:'Veja os produtos e coleções atuais.',content:'Explore a montra digital e fale connosco para obter informações mais detalhadas.',items:['Explorar produtos|/produtos'],order:4,status:'published'},
    {id:'contact-hero',pageSlug:'contacto',type:'page-header',eyebrow:'Fale connosco',title:'Vamos começar uma conversa.',content:'Dúvidas, informação sobre produtos, ideias, projetos ou uma conversa comercial.',order:1,status:'published'},
    {id:'contact-form',pageSlug:'contacto',type:'form',eyebrow:'Contactos',title:'Envie-nos uma mensagem',content:'Responderemos assim que possível.',order:2,status:'published'},
    {id:'products-header',pageSlug:'produtos',type:'page-header',eyebrow:'Catálogo informativo',title:'Produtos',content:'Descubra exemplos da seleção AM Moreira. Para informações, disponibilidade ou projetos, contacte-nos.',order:1,status:'published'},
    {id:'collections-header',pageSlug:'colecoes',type:'page-header',eyebrow:'Editorial',title:'Coleções',content:'Narrativas visuais organizadas por ano, estação ou conceito.',order:1,status:'published'},
    {id:'events-header',pageSlug:'eventos',type:'page-header',eyebrow:'Presença da marca',title:'Feiras & Eventos',content:'Consulte onde poderá encontrar a AM Moreira.',order:1,status:'published'},
    {id:'gallery-header',pageSlug:'galeria',type:'page-header',eyebrow:'Universo visual',title:'Galeria',content:'Produtos, detalhes, presença e identidade AM Moreira.',order:1,status:'published'},
  ],
  products: [
    {id:'product-classic',name:'Linha Clássica',reference:'AM · 01',description:'Uma proposta intemporal, pensada para conjugar conforto e elegância em diferentes momentos.',image:'/brand/cartao-visita.jpg',categoryId:'footwear',featured:true,status:'published',order:1},
    {id:'product-urban',name:'Linha Urbana',reference:'AM · 02',description:'Detalhes contemporâneos e versatilidade para acompanhar um ritmo mais dinâmico.',image:'/brand/cartao-visita.jpg',categoryId:'boots',featured:true,status:'published',order:2},
    {id:'product-essentials',name:'Essenciais AM',reference:'AM · 03',description:'Peças selecionadas para uma utilização prática, confortável e com identidade.',image:'/brand/cartao-visita.jpg',categoryId:'leather-goods',featured:true,status:'published',order:3},
  ],
  collections: [
    {id:'collection-signature',name:'Assinatura',season:'Seleção permanente',description:'Uma seleção de peças com linhas equilibradas e identidade duradoura.',image:'/brand/cartao-visita.jpg',featured:true,status:'published',order:1},
    {id:'collection-everyday',name:'Todos os dias',season:'Conforto & versatilidade',description:'Propostas fáceis de combinar, pensadas para acompanhar a rotina.',image:'/brand/cartao-visita.jpg',featured:true,status:'published',order:2},
    {id:'collection-details',name:'Detalhes',season:'Acessórios',description:'Complementos que acrescentam funcionalidade e um toque pessoal.',image:'/brand/cartao-visita.jpg',featured:true,status:'published',order:3},
  ],
  events: [
    {id:'event-paredes',name:'AM Moreira em Paredes',city:'Paredes',startDate:'Datas a anunciar',description:'Acompanhe esta área para saber onde poderá conhecer a nossa seleção presencialmente.',featured:true,status:'upcoming',order:1},
    {id:'event-lousada',name:'AM Moreira em Lousada',city:'Lousada',startDate:'Datas a anunciar',description:'Uma oportunidade para descobrir novidades e falar diretamente com a nossa equipa.',featured:true,status:'upcoming',order:2},
    {id:'event-penafiel',name:'AM Moreira em Penafiel',city:'Penafiel',startDate:'Datas a anunciar',description:'Brevemente com mais detalhes sobre local, data e seleção disponível.',featured:true,status:'upcoming',order:3},
  ],
  gallery: [
    {id:'gallery-brand',title:'Identidade AM Moreira',images:['/brand/cartao-visita.jpg'],status:'published',order:1},
    {id:'gallery-details',title:'Detalhes da marca',images:['/brand/logo-preto.png','/brand/monograma-preto.png'],status:'published',order:2},
  ], contacts: [], auditLogs: [], users: [],
}
